version: '3.8'
services:
  bot:
    build: .
    container_name: bot-hospital-ecco
    restart: always
    environment:
      - DISCORD_TOKEN=O_SEU_NOVO_TOKEN_AQUI
      - PANEL_CHANNEL_ID=1515846128493658142
      - RANK_CHANNEL_ID=1515852084480839850
      - LOGS_CHANNEL_ID=1515846898156834956
      - REMOVE_PANEL_CHANNEL_ID=1515846758456885400
